
#' Power Generated by an Automobile
#' 
#' This function determines the power required to keep a car moving at a given speed
#' @param V vehicle speed (m/s)
#' @param m vehicle mass (kg)
#' @param A surface area of car (m^2)
#' @param g acceleration due to gravity (m/s^2) default = 9.8
#' @param p_air density of air (kg/m^3) default = 1.2
#' @param crolling rolling resistive coefficient default = 0.015
#' @param cdrag aerodynamic resistive coefficient default = 0.3
#' @return P power (Watts)
#' 
#' function definition
auto_power = function(V, m, A, crolling = 0.015, cdrag = 0.3, g = 9.8, p_air = 1.2) {
  result = crolling * m * g * V + 0.5 * A * p_air * cdrag * V^3
  return(result)
}